engines:
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true

ratings:
  paths:
    - "**.go"
    - "**.js"
    - "**.css"

exclude_paths:
    - config/**
    - vendor/**