# .goreleaser.yml
# Build customization
version: 2

project_name: mmock

builds:
  - id: mmock
    main: cmd/mmock/main.go
    binary: mmock
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
     - -X main.VERSION={{.Version}}

archives:
  - id: mmock
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    formats:
      - tar.gz
      - zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

dockers:
  - image_templates:
      - "jordimartin/mmock:{{ .Tag }}-amd64"
      - "jordimartin/mmock:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: amd64
    goos: linux
    extra_files:
      - tls/server.crt
      - tls/server.key
  - image_templates:
      - "jordimartin/mmock:{{ .Tag }}-arm64"
      - "jordimartin/mmock:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm64
    goos: linux
    extra_files:
      - tls/server.crt
      - tls/server.key

docker_manifests:
  - name_template: "jordimartin/mmock:{{ .Tag }}"
    image_templates:
      - "jordimartin/mmock:{{ .Tag }}-amd64"
      - "jordimartin/mmock:{{ .Tag }}-arm64"
  - name_template: "jordimartin/mmock:latest"
    image_templates:
      - "jordimartin/mmock:latest-amd64"
      - "jordimartin/mmock:latest-arm64"

release:
  github:
    owner: jmartin82
    name: mmock
  draft: false

changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - rollback