# .goreleaser.yml
# Build customization
version: 2

project_name: mmock

builds:
  - id: mmock
    main: cmd/mmock/main.go
    binary: mmock
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
     - -X main.VERSION={{.Version}}

archives:
  - id: mmock
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

dockers_v2:
  - id: mmock
    ids:
      - mmock
    dockerfile: Dockerfile
    images:
      - "jordimartin/mmock"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
    extra_files:
      - tls/server.crt
      - tls/server.key

release:
  github:
    owner: jmartin82
    name: mmock
  draft: false

changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - rollback