description: "Example for proxy usage and get with parameters (param 2 can have any value)"

request:
  method: GET
  path: /proxy_get
  queryStringParameters:
    param1:
      - 1
    param2:
      - "*"
control:
  proxyBaseURL: "http://www.mocky.io/v2/57e1b4d1110000b90556f51c"
