request:
  method: POST
  path: /events
response:
  statusCode: 200
  headers:
    Content-Type:
      - "text/event-stream"
    Connection:
      - "keep-alive"
    Cache-Control:
      - "no-cache"
  body: >
    [
      {  
        "test":"1"
      },
      {  
        "test":"2"
      },
      {  
        "test":"3"
      },
      {  
        "test":"4"
      },
      {  
        "test":"5"
      },
      {  
        "test":"6"
      },
      {  
        "test":"7"
      },
      {  
        "test":"8"
      },
      {  
        "test":"9"
      }
    ]
